project_id = "hxnkgslrpkkdtddhckxp"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://hxnkgslrpkkdtddhckxp.supabase.co/auth/v1/callback"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54322
major_version = 15

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
file_size_limit = "50MiB"

[edge-runtime]
policy = "per_worker"

[functions.data-collector]
verify_jwt = true

[functions.export-data]
verify_jwt = true

[functions.import-data]
verify_jwt = true