project_id = "gcoorbcglxczmukzcmqs"

[functions.client-logic]
verify_jwt = false

[functions.gemini-research]
verify_jwt = false

[functions.data-collector]
verify_jwt = false

[functions.gdpr-processor]
verify_jwt = false