project_id = "gcoorbcglxczmukzcmqs"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[functions.stefan-ai-chat]
verify_jwt = false

[functions.send-message-notification]
verify_jwt = true

[functions.send-password-reset]
verify_jwt = false

[auth]
enabled = true