project_id = "gcoorbcglxczmukzcmqs"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = "ipv6"
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54321
file_size_limit = "50MiB"
image_transformation = { enabled = true }

[auth]
enabled = true
port = 54321
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 1800
enable_manual_linking = false
enable_signup = true
enable_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
secure_password_change = false

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }}"

[functions.auth-webhook]
verify_jwt = false

[functions.user-deletion]
verify_jwt = true

[functions.user-soft-delete]
verify_jwt = true

[functions.user-reactivate]
verify_jwt = true

[functions.unified-ai-orchestrator]
verify_jwt = false

[functions.stefan-ai-chat]
verify_jwt = true

[functions.admin-password-reset]
verify_jwt = true

[functions.unified-invitations]
verify_jwt = true

[functions.send-invitation]
verify_jwt = true

[functions.send-invitations]
verify_jwt = true

[functions.send-simple-invitation]
verify_jwt = true

[edge_runtime]
policy = "per_worker"
inspector_port = 8083