import { serve } from "https://deno.land/std@0.190.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.53.0";
import { Resend } from "npm:resend@4.0.0";

const resendApiKey = Deno.env.get("RESEND_API_KEY");
console.log("RESEND_API_KEY exists:", !!resendApiKey);
console.log("RESEND_API_KEY length:", resendApiKey?.length || 0);

if (!resendApiKey) {
  console.error("RESEND_API_KEY environment variable is not set");
}
const resend = new Resend(resendApiKey);

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface InvitationRequest {
  email: string;
  role?: string;
  inviterName?: string;
}

const handler = async (req: Request): Promise<Response> => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Check if Resend API key is configured
    if (!resendApiKey) {
      console.error("RESEND_API_KEY environment variable is not set");
      return new Response(
        JSON.stringify({ 
          error: 'Email service not configured. Please add RESEND_API_KEY to Supabase secrets.',
          details: 'Contact administrator to set up email service.'
        }),
        {
          status: 500,
          headers: { "Content-Type": "application/json", ...corsHeaders },
        }
      );
    }

    const { email, role = 'client', inviterName }: InvitationRequest = await req.json();

    // Get the authorization header
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      throw new Error('No authorization header');
    }

    // Create Supabase client with the user's session
    const supabase = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
      {
        global: {
          headers: { Authorization: authHeader },
        },
      }
    );

    // Get the current user
    const { data: { user }, error: userError } = await supabase.auth.getUser();
    if (userError || !user) {
      throw new Error('Unauthorized');
    }

    // Create invitation in database (token will be auto-generated by trigger)
    const { data: invitation, error: invitationError } = await supabase
      .from('invitations')
      .insert({
        email,
        invited_role: role,
        invited_by: user.id,
      })
      .select()
      .single();

    if (invitationError) {
      throw invitationError;
    }

    // Generate invitation URL
    const baseUrl = req.headers.get('origin') || 'https://gcoorbcglxczmukzcmqs.supabase.co';
    const invitationUrl = `${baseUrl}/invitation/${invitation.token}`;

    console.log("Attempting to send email to:", email);
    console.log("Using sender:", "SHIMM <onboarding@resend.dev>");
    
    // Send invitation email
    const { data: emailResult, error: emailError } = await resend.emails.send({
      from: "SHIMM <onboarding@resend.dev>", // Using Resend's verified domain for testing
      to: [email],
      subject: `Inbjudan till SHIMM från ${inviterName || 'teamet'}`,
      html: `
        <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto;">
          <h1 style="color: #3B82F6;">Välkommen till SHIMM!</h1>
          
          <p>Hej!</p>
          
          <p>Du har bjudits in att gå med i SHIMM av ${inviterName || 'teamet'}. För att komma igång, klicka på länken nedan för att skapa ditt konto:</p>
          
          <div style="text-align: center; margin: 30px 0;">
            <a href="${invitationUrl}" 
               style="background-color: #3B82F6; color: white; padding: 12px 24px; text-decoration: none; border-radius: 8px; display: inline-block;">
              Skapa konto
            </a>
          </div>
          
          <p>Eller kopiera och klistra in denna länk i din webbläsare:</p>
          <p style="background-color: #f5f5f5; padding: 10px; border-radius: 4px; word-break: break-all;">
            ${invitationUrl}
          </p>
          
          <p><strong>Obs:</strong> Denna inbjudan är giltig i 7 dagar.</p>
          
          <p>Vi ser fram emot att ha dig med i teamet!</p>
          
          <p>Vänliga hälsningar,<br>SHIMM-teamet</p>
        </div>
      `,
    });

    console.log("Email send response:", { emailResult, emailError });
    console.log("Email result details:", JSON.stringify(emailResult, null, 2));
    console.log("Email error details:", JSON.stringify(emailError, null, 2));
    
    if (emailError) {
      console.error("Failed to send invitation email:", emailError);
      
      // Delete the invitation since email failed
      await supabase
        .from('invitations')
        .delete()
        .eq('id', invitation.id);
        
      throw new Error(`Email sending failed: ${emailError.message || JSON.stringify(emailError)}`);
    }

    if (!emailResult || !emailResult.id) {
      console.error("No email result returned:", emailResult);
      
      // Delete the invitation since email failed
      await supabase
        .from('invitations')
        .delete()
        .eq('id', invitation.id);
        
      throw new Error('Email sending failed: No result returned from email service');
    }

    console.log("Invitation email sent successfully:", emailResult);

    return new Response(
      JSON.stringify({ 
        success: true, 
        invitationId: invitation.id,
        invitationUrl,
        emailId: emailResult.id
      }),
      {
        status: 200,
        headers: {
          "Content-Type": "application/json",
          ...corsHeaders,
        },
      }
    );
  } catch (error: any) {
    console.error("Error in send-invitation function:", error);
    return new Response(
      JSON.stringify({ error: error.message }),
      {
        status: 500,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      }
    );
  }
};

serve(handler);